CREATE DATABASE EstacionApi;

CREATE TABLE IF NOT EXISTS usuario(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    correo text NOT NULL,
    password text NOT NULL
);
CREATE TABLE IF NOT EXISTS estacion(
    codigo integer PRIMARY KEY,
    nombre text,
    latitud text,
    longitud text,
    altura text
);

CREATE TABLE IF NOT EXISTS informe(
    id_informe integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    codigo INTEGER REFERENCES estacion(codigo),
    dia integer,
    mes integer,
    ano integer,
    tmax numeric,
    tmin numeric,
    precip numeric
);
