CREATE DATABASE EstApi2;

CREATE TABLE IF NOT EXISTS usuario(
    id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    correo text NOT NULL,
    password text NOT NULL
);
CREATE TABLE IF NOT EXISTS estacion(
    id_estacion integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text NOT NULL,
    latitud text NULL,
    longitud text NULL,
    altura text NULL
);
CREATE TABLE IF NOT EXISTS mes(
    id_mes integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    mes text NOT NULL,
    numero integer NOT NULL
);
CREATE TABLE IF NOT EXISTS ano(
    id_ano integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    ano text NOT NULL
);
CREATE TABLE IF NOT EXISTS indicador(
    id_indicador integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    nombre text,
    num INTEGER
);
CREATE TABLE IF NOT EXISTS informe(
    id_informe integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    id_ano INTEGER REFERENCES Ano(id_ano),
    id_mes INTEGER REFERENCES Mes(id_mes),
    id_indicador INTEGER REFERENCES indicador(id_indicador),
	dia integer,
	num integer
);

INSERT INTO mes (mes, numero) VALUES ('enero', '1');
INSERT INTO mes (mes, numero) VALUES ('febrero', '2');
INSERT INTO mes (mes, numero) VALUES ('marzo', '3');
INSERT INTO mes (mes, numero) VALUES ('abril', '4');
INSERT INTO mes (mes, numero) VALUES ('mayo', '5');
INSERT INTO mes (mes, numero) VALUES ('junio', '6');
INSERT INTO mes (mes, numero) VALUES ('julio', '7');
INSERT INTO mes (mes, numero) VALUES ('agosto', '8');
INSERT INTO mes (mes, numero) VALUES ('septiembre', '9');
INSERT INTO mes (mes, numero) VALUES ('octubre', '10');
INSERT INTO mes (mes, numero) VALUES ('noviembre', '11');
INSERT INTO mes (mes, numero) VALUES ('diciembre', '12');

INSERT INTO indicador (nombre) VALUES ('precipitacion');
INSERT INTO indicador (nombre) VALUES ('tem_maxima');
INSERT INTO indicador (nombre) VALUES ('temp_minima');



INSERT INTO users (name, email) VALUES
('Alonso', 'alonso.pinoo@gmail.com');